export const contactUs = [
    {
        link: 'tel:+573228725091',
        value: '+57 322 872 5091',
        svg: '/svg/phone-svgrepo-com.svg'
    },
    {
        link: 'mailto:montunobirds@gmail.com',
        value: 'montunobirds@gmail.com',
        svg: '/svg/mail-pencil-svgrepo-com.svg'
    },
    {
        link: 'https://maps.app.goo.gl/fKJRrz3RQ6Nbedyy5',
        value: 'ubicación',
        svg: '/svg/map-pin-alt-svgrepo-com.svg'
    }
]
export const aire = [
    '66.webp',
    'Alcaravan_Venezolano.webp',
    'Arrendajo_Culiamarillo.webp',
    'Aruco.webp',
    'Atrapamoscas_Cuidapuentes.webp',
    'Atrapamoscas_Garrochero.webp',
    'Atrapamoscas_Veteado.webp',
    'Azulejo_Comun.webp',
    'Bandurria_Aliblanca.webp',
    'Barranquero_Coronado.webp',
    'Biemparado_Grande.webp',
    'Bujio.webp',
    'Cabeza_De_Hueso_1.webp',    
    'Canario_Coronado.webp',
    'Canario_Sabanero.webp',
    'Cangrejero_Grande_1.webp',    
    'Caracara_Quebrantahuesos.webp',
    'Cardenal_Pantanero.webp',
    'Carpintero_Habado_1.webp',    'Carpintero_Marcial.webp',
    'Carpintero_Real.webp',
    'Carriqui_Violaceo.webp',
    'Cernicola_Americano.webp',
    'Chenchena.webp',
    'Chirlobirlo.webp',
    'Coquito.webp',
    'Corocora.webp',
    'Espatula_Rosada.webp',
    'Espiguero_Ladrillo.webp',
    'Eufonia_Gorgiamarilla.webp',
    'Eufonia_Gorgipurpura.webp',
    'Garrapatero_Piquiliso.webp',
    'Garza_Azul_1.webp',    
    'Garza_Del_Sol.webp',
    'Garza_Patiamarilla.webp',
    'Garza_Real.webp',
    'Garza_Silbadora.webp',
    'Garzon_Azul.webp',
    'Gavilan_Caminero_1.webp',    
    'Guacharaca_Variable.webp',
    'Guala_Cabecirroja.webp',
    'Guala_Sabanera.webp',
    'Ibis_Verde.webp',
    'Jabiru1.webp',
    'Jabiru2.webp',
    'Jacamar_Lugubre_1.webp',    
    'Lora_Cabeciamarilla.webp',
    'Martin_Pescador_Grande.webp',
    'Mielero_Comun.webp',
    'Mochuelo_Conejo.webp',
    'Monjita_Pantanera.webp',
    'Paloma_Morada.webp',
    'Parlotero_Malcasado.webp',
    'Pellar_Playero.webp',
    'Pellar_Teru_Teru.webp',
    'Perdiz_Chilindra.webp',
    'Perico_Carisucio.webp',
    'Periquito_De_Anteojos.webp',
    'Pichi_Bandirojo_1.webp',    
    'Pigua.webp',
    'Pisingo.webp',
    'Polla_Azul.webp',
    'Sinsonte_Comun_1.webp',    
    'Siriri_Comun.webp',
    'Siriri_Tijereton.webp',
    'Soldadito.webp',
    'Tangara_Triguera_1.webp',    
    'Toche_Negro.webp',
    'Tordo_Llanero.webp',
    'Tortolita_Escamada.webp',
    'Trogon_Coliblanco_1.webp',    
    'Tucan_Silbador.webp',
    'Turpial_Lagunero.webp',
]